/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import requirementsXtext.reqXtext.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ReqXtextFactoryImpl extends EFactoryImpl implements ReqXtextFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ReqXtextFactory init()
  {
    try
    {
      ReqXtextFactory theReqXtextFactory = (ReqXtextFactory)EPackage.Registry.INSTANCE.getEFactory(ReqXtextPackage.eNS_URI);
      if (theReqXtextFactory != null)
      {
        return theReqXtextFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ReqXtextFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReqXtextFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ReqXtextPackage.XCONTAINER: return createXContainer();
      case ReqXtextPackage.XAGENT: return createXAgent();
      case ReqXtextPackage.XPROVIDER: return createXProvider();
      case ReqXtextPackage.XCONSUMER: return createXConsumer();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XContainer createXContainer()
  {
    XContainerImpl xContainer = new XContainerImpl();
    return xContainer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XAgent createXAgent()
  {
    XAgentImpl xAgent = new XAgentImpl();
    return xAgent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XProvider createXProvider()
  {
    XProviderImpl xProvider = new XProviderImpl();
    return xProvider;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XConsumer createXConsumer()
  {
    XConsumerImpl xConsumer = new XConsumerImpl();
    return xConsumer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReqXtextPackage getReqXtextPackage()
  {
    return (ReqXtextPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ReqXtextPackage getPackage()
  {
    return ReqXtextPackage.eINSTANCE;
  }

} //ReqXtextFactoryImpl
