/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import requirementsXtext.reqXtext.ReqXtextPackage;
import requirementsXtext.reqXtext.XAgent;
import requirementsXtext.reqXtext.XContainer;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XContainer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link requirementsXtext.reqXtext.impl.XContainerImpl#getAgents <em>Agents</em>}</li>
 * </ul>
 *
 * @generated
 */
public class XContainerImpl extends MinimalEObjectImpl.Container implements XContainer
{
  /**
   * The cached value of the '{@link #getAgents() <em>Agents</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgents()
   * @generated
   * @ordered
   */
  protected EList<XAgent> agents;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XContainerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReqXtextPackage.Literals.XCONTAINER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<XAgent> getAgents()
  {
    if (agents == null)
    {
      agents = new EObjectContainmentEList<XAgent>(XAgent.class, this, ReqXtextPackage.XCONTAINER__AGENTS);
    }
    return agents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ReqXtextPackage.XCONTAINER__AGENTS:
        return ((InternalEList<?>)getAgents()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ReqXtextPackage.XCONTAINER__AGENTS:
        return getAgents();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ReqXtextPackage.XCONTAINER__AGENTS:
        getAgents().clear();
        getAgents().addAll((Collection<? extends XAgent>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ReqXtextPackage.XCONTAINER__AGENTS:
        getAgents().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ReqXtextPackage.XCONTAINER__AGENTS:
        return agents != null && !agents.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //XContainerImpl
