/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext.impl;

import org.eclipse.emf.ecore.EClass;

import requirementsXtext.reqXtext.ReqXtextPackage;
import requirementsXtext.reqXtext.XConsumer;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XConsumer</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XConsumerImpl extends XAgentImpl implements XConsumer
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XConsumerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReqXtextPackage.Literals.XCONSUMER;
  }

} //XConsumerImpl
