/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext.impl;

import org.eclipse.emf.ecore.EClass;

import requirementsXtext.reqXtext.ReqXtextPackage;
import requirementsXtext.reqXtext.XProvider;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XProvider</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XProviderImpl extends XAgentImpl implements XProvider
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XProviderImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReqXtextPackage.Literals.XPROVIDER;
  }

} //XProviderImpl
