/*
 * generated by Xtext 2.11.0
 */
package xtextImplementation.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractXtextImplValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(xtextImplementation.xtextImpl.XtextImplPackage.eINSTANCE);
		return result;
	}
	
}
