/*
 * generated by Xtext 2.11.0
 */
package xtextImplementation.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import xtextImplementation.ide.contentassist.antlr.internal.InternalXtextImplParser;
import xtextImplementation.services.XtextImplGrammarAccess;

public class XtextImplParser extends AbstractContentAssistParser {

	@Inject
	private XtextImplGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalXtextImplParser createParser() {
		InternalXtextImplParser result = new InternalXtextImplParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getNetworkElementAccess().getAlternatives(), "rule__NetworkElement__Alternatives");
					put(grammarAccess.getXDeviceAccess().getAlternatives(), "rule__XDevice__Alternatives");
					put(grammarAccess.getXCableAccess().getAlternatives(), "rule__XCable__Alternatives");
					put(grammarAccess.getBoolAccess().getAlternatives(), "rule__Bool__Alternatives");
					put(grammarAccess.getConnectionsAccess().getGroup(), "rule__Connections__Group__0");
					put(grammarAccess.getConnectionsAccess().getGroup_1(), "rule__Connections__Group_1__0");
					put(grammarAccess.getConnectionsAccess().getGroup_1_3(), "rule__Connections__Group_1_3__0");
					put(grammarAccess.getConnectionsAccess().getGroup_2(), "rule__Connections__Group_2__0");
					put(grammarAccess.getConnectionsAccess().getGroup_2_3(), "rule__Connections__Group_2_3__0");
					put(grammarAccess.getCableAttributesAccess().getGroup(), "rule__CableAttributes__Group__0");
					put(grammarAccess.getCableAttributesAccess().getGroup_7(), "rule__CableAttributes__Group_7__0");
					put(grammarAccess.getXServerAccess().getGroup(), "rule__XServer__Group__0");
					put(grammarAccess.getXComputerAccess().getGroup(), "rule__XComputer__Group__0");
					put(grammarAccess.getXRouterAccess().getGroup(), "rule__XRouter__Group__0");
					put(grammarAccess.getXCopperCableAccess().getGroup(), "rule__XCopperCable__Group__0");
					put(grammarAccess.getXGlassFiberCableAccess().getGroup(), "rule__XGlassFiberCable__Group__0");
					put(grammarAccess.getXContainerAccess().getElementsAssignment(), "rule__XContainer__ElementsAssignment");
					put(grammarAccess.getConnectionsAccess().getIncomingAssignment_1_2(), "rule__Connections__IncomingAssignment_1_2");
					put(grammarAccess.getConnectionsAccess().getIncomingAssignment_1_3_1(), "rule__Connections__IncomingAssignment_1_3_1");
					put(grammarAccess.getConnectionsAccess().getOutgoingAssignment_2_2(), "rule__Connections__OutgoingAssignment_2_2");
					put(grammarAccess.getConnectionsAccess().getOutgoingAssignment_2_3_1(), "rule__Connections__OutgoingAssignment_2_3_1");
					put(grammarAccess.getCableAttributesAccess().getSpeedAssignment_2(), "rule__CableAttributes__SpeedAssignment_2");
					put(grammarAccess.getCableAttributesAccess().getEndPoint1Assignment_4(), "rule__CableAttributes__EndPoint1Assignment_4");
					put(grammarAccess.getCableAttributesAccess().getEndPoint2Assignment_6(), "rule__CableAttributes__EndPoint2Assignment_6");
					put(grammarAccess.getCableAttributesAccess().getIsDuplexAssignment_7_1(), "rule__CableAttributes__IsDuplexAssignment_7_1");
					put(grammarAccess.getXServerAccess().getNameAssignment_1(), "rule__XServer__NameAssignment_1");
					put(grammarAccess.getXServerAccess().getMaxSlotsAssignment_4(), "rule__XServer__MaxSlotsAssignment_4");
					put(grammarAccess.getXServerAccess().getMTBFAssignment_6(), "rule__XServer__MTBFAssignment_6");
					put(grammarAccess.getXServerAccess().getConnectionsAssignment_7(), "rule__XServer__ConnectionsAssignment_7");
					put(grammarAccess.getXComputerAccess().getNameAssignment_1(), "rule__XComputer__NameAssignment_1");
					put(grammarAccess.getXComputerAccess().getConnectionsAssignment_3(), "rule__XComputer__ConnectionsAssignment_3");
					put(grammarAccess.getXRouterAccess().getNameAssignment_1(), "rule__XRouter__NameAssignment_1");
					put(grammarAccess.getXRouterAccess().getMaxSpeedAssignment_4(), "rule__XRouter__MaxSpeedAssignment_4");
					put(grammarAccess.getXRouterAccess().getConnectionsAssignment_5(), "rule__XRouter__ConnectionsAssignment_5");
					put(grammarAccess.getXCopperCableAccess().getNameAssignment_1(), "rule__XCopperCable__NameAssignment_1");
					put(grammarAccess.getXCopperCableAccess().getCableAttributesAssignment_3(), "rule__XCopperCable__CableAttributesAssignment_3");
					put(grammarAccess.getXGlassFiberCableAccess().getNameAssignment_1(), "rule__XGlassFiberCable__NameAssignment_1");
					put(grammarAccess.getXGlassFiberCableAccess().getCableAttributesAssignment_3(), "rule__XGlassFiberCable__CableAttributesAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public XtextImplGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XtextImplGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
