/**
 *
 * $Id$
 */
package implementation.validation;

import implementation.Cable;
import implementation.Device;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link implementation.Container}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerValidator {
	boolean validate();

	boolean validateDevices(EList<Device> value);
	boolean validateCables(EList<Cable> value);
}
