/**
 *
 * $Id$
 */
package implementation.validation;

import java.math.BigInteger;
import requirements.Provider;

/**
 * A sample validator interface for {@link implementation.Server}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServerValidator {
	boolean validate();

	boolean validateProvider(Provider value);

	boolean validateMaxSlots(BigInteger value);

	boolean validateMTBF(BigInteger value);
}
