/*
 * generated by Xtext 2.12.0
 */
package xtextImplementation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XtextImplStandaloneSetup extends XtextImplStandaloneSetupGenerated {

	def static void doSetup() {
		new XtextImplStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
