/*
 * generated by Xtext 2.11.0
 */
package requirementsXtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import requirementsXtext.reqXtext.ReqXtextPackage;
import requirementsXtext.reqXtext.XConsumer;
import requirementsXtext.reqXtext.XContainer;
import requirementsXtext.reqXtext.XProvider;
import requirementsXtext.services.ReqXtextGrammarAccess;

@SuppressWarnings("all")
public class ReqXtextSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ReqXtextGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ReqXtextPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ReqXtextPackage.XCONSUMER:
				sequence_XConsumer(context, (XConsumer) semanticObject); 
				return; 
			case ReqXtextPackage.XCONTAINER:
				sequence_XContainer(context, (XContainer) semanticObject); 
				return; 
			case ReqXtextPackage.XPROVIDER:
				sequence_XProvider(context, (XProvider) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     XAgent returns XConsumer
	 *     XConsumer returns XConsumer
	 *
	 * Constraint:
	 *     (name=ID speed=EBigInteger)
	 */
	protected void sequence_XConsumer(ISerializationContext context, XConsumer semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ReqXtextPackage.Literals.XAGENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ReqXtextPackage.Literals.XAGENT__NAME));
			if (transientValues.isValueTransient(semanticObject, ReqXtextPackage.Literals.XAGENT__SPEED) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ReqXtextPackage.Literals.XAGENT__SPEED));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXConsumerAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXConsumerAccess().getSpeedEBigIntegerParserRuleCall_4_0(), semanticObject.getSpeed());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     XContainer returns XContainer
	 *
	 * Constraint:
	 *     agents+=XAgent+
	 */
	protected void sequence_XContainer(ISerializationContext context, XContainer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     XAgent returns XProvider
	 *     XProvider returns XProvider
	 *
	 * Constraint:
	 *     (name=ID speed=EBigInteger)
	 */
	protected void sequence_XProvider(ISerializationContext context, XProvider semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ReqXtextPackage.Literals.XAGENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ReqXtextPackage.Literals.XAGENT__NAME));
			if (transientValues.isValueTransient(semanticObject, ReqXtextPackage.Literals.XAGENT__SPEED) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ReqXtextPackage.Literals.XAGENT__SPEED));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXProviderAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXProviderAccess().getSpeedEBigIntegerParserRuleCall_4_0(), semanticObject.getSpeed());
		feeder.finish();
	}
	
	
}
