/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import xtextImplementation.xtextImpl.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see xtextImplementation.xtextImpl.XtextImplPackage
 * @generated
 */
public class XtextImplAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static XtextImplPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XtextImplAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = XtextImplPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XtextImplSwitch<Adapter> modelSwitch =
    new XtextImplSwitch<Adapter>()
    {
      @Override
      public Adapter caseXContainer(XContainer object)
      {
        return createXContainerAdapter();
      }
      @Override
      public Adapter caseNetworkElements(NetworkElements object)
      {
        return createNetworkElementsAdapter();
      }
      @Override
      public Adapter caseXDevice(XDevice object)
      {
        return createXDeviceAdapter();
      }
      @Override
      public Adapter caseXCable(XCable object)
      {
        return createXCableAdapter();
      }
      @Override
      public Adapter caseConnections(Connections object)
      {
        return createConnectionsAdapter();
      }
      @Override
      public Adapter caseCableAttributes(CableAttributes object)
      {
        return createCableAttributesAdapter();
      }
      @Override
      public Adapter caseXServer(XServer object)
      {
        return createXServerAdapter();
      }
      @Override
      public Adapter caseXComputer(XComputer object)
      {
        return createXComputerAdapter();
      }
      @Override
      public Adapter caseXRouter(XRouter object)
      {
        return createXRouterAdapter();
      }
      @Override
      public Adapter caseXCopperCable(XCopperCable object)
      {
        return createXCopperCableAdapter();
      }
      @Override
      public Adapter caseXGlassFiberCable(XGlassFiberCable object)
      {
        return createXGlassFiberCableAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.XContainer <em>XContainer</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.XContainer
   * @generated
   */
  public Adapter createXContainerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.NetworkElements <em>Network Elements</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.NetworkElements
   * @generated
   */
  public Adapter createNetworkElementsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.XDevice <em>XDevice</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.XDevice
   * @generated
   */
  public Adapter createXDeviceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.XCable <em>XCable</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.XCable
   * @generated
   */
  public Adapter createXCableAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.Connections <em>Connections</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.Connections
   * @generated
   */
  public Adapter createConnectionsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.CableAttributes <em>Cable Attributes</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.CableAttributes
   * @generated
   */
  public Adapter createCableAttributesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.XServer <em>XServer</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.XServer
   * @generated
   */
  public Adapter createXServerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.XComputer <em>XComputer</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.XComputer
   * @generated
   */
  public Adapter createXComputerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.XRouter <em>XRouter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.XRouter
   * @generated
   */
  public Adapter createXRouterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.XCopperCable <em>XCopper Cable</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.XCopperCable
   * @generated
   */
  public Adapter createXCopperCableAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link xtextImplementation.xtextImpl.XGlassFiberCable <em>XGlass Fiber Cable</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see xtextImplementation.xtextImpl.XGlassFiberCable
   * @generated
   */
  public Adapter createXGlassFiberCableAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //XtextImplAdapterFactory
