/*
 * generated by Xtext 2.11.0
 */
package requirementsXtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReqXtextScopeProvider extends DelegatingScopeProvider {
}
