/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import requirementsXtext.ui.AbstractReqXtextUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ReqXtextUiModule extends AbstractReqXtextUiModule {
  public ReqXtextUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
