/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.ide;

import requirementsXtext.ide.AbstractReqXtextIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ReqXtextIdeModule extends AbstractReqXtextIdeModule {
}
