/**
 * generated by Xtext 2.12.0
 */
package xtextImplementation.ide;

import xtextImplementation.ide.AbstractXtextImplIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XtextImplIdeModule extends AbstractXtextImplIdeModule {
}
