/**
 * generated by Xtext 2.12.0
 */
package xtextImplementation.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import xtextImplementation.XtextImplRuntimeModule;
import xtextImplementation.XtextImplStandaloneSetup;
import xtextImplementation.ide.XtextImplIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class XtextImplIdeSetup extends XtextImplStandaloneSetup {
  @Override
  public Injector createInjector() {
    XtextImplRuntimeModule _xtextImplRuntimeModule = new XtextImplRuntimeModule();
    XtextImplIdeModule _xtextImplIdeModule = new XtextImplIdeModule();
    return Guice.createInjector(Modules2.mixin(_xtextImplRuntimeModule, _xtextImplIdeModule));
  }
}
