/*
 * generated by Xtext 2.11.0
 */
package xtextImplementation.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtextImplementation.parser.antlr.internal.InternalXtextImplParser;
import xtextImplementation.services.XtextImplGrammarAccess;

public class XtextImplParser extends AbstractAntlrParser {

	@Inject
	private XtextImplGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXtextImplParser createParser(XtextTokenStream stream) {
		return new InternalXtextImplParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "XContainer";
	}

	public XtextImplGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XtextImplGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
