/*
 * generated by Xtext 2.11.0
 */
package xtextImplementation.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class XtextImplGrammarAccess extends AbstractGrammarElementFinder {
	
	public class XContainerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.XContainer");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsNetworkElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//XContainer:
		//	elements+=NetworkElement*;
		@Override public ParserRule getRule() { return rule; }
		
		//elements+=NetworkElement*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//NetworkElement
		public RuleCall getElementsNetworkElementParserRuleCall_0() { return cElementsNetworkElementParserRuleCall_0; }
	}
	public class NetworkElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.NetworkElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cXDeviceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cXCableParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//NetworkElement NetworkElements:
		//	XDevice | XCable;
		@Override public ParserRule getRule() { return rule; }
		
		//XDevice | XCable
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//XDevice
		public RuleCall getXDeviceParserRuleCall_0() { return cXDeviceParserRuleCall_0; }
		
		//XCable
		public RuleCall getXCableParserRuleCall_1() { return cXCableParserRuleCall_1; }
	}
	public class XDeviceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.XDevice");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cXServerParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cXComputerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cXRouterParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//XDevice:
		//	XServer | XComputer | XRouter;
		@Override public ParserRule getRule() { return rule; }
		
		//XServer | XComputer | XRouter
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//XServer
		public RuleCall getXServerParserRuleCall_0() { return cXServerParserRuleCall_0; }
		
		//XComputer
		public RuleCall getXComputerParserRuleCall_1() { return cXComputerParserRuleCall_1; }
		
		//XRouter
		public RuleCall getXRouterParserRuleCall_2() { return cXRouterParserRuleCall_2; }
	}
	public class XCableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.XCable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cXCopperCableParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cXGlassFiberCableParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//XCable:
		//	XCopperCable | XGlassFiberCable;
		@Override public ParserRule getRule() { return rule; }
		
		//XCopperCable | XGlassFiberCable
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//XCopperCable
		public RuleCall getXCopperCableParserRuleCall_0() { return cXCopperCableParserRuleCall_0; }
		
		//XGlassFiberCable
		public RuleCall getXGlassFiberCableParserRuleCall_1() { return cXGlassFiberCableParserRuleCall_1; }
	}
	public class ConnectionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.Connections");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConnectionsAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cIncomingKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cIncomingAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final CrossReference cIncomingXCableCrossReference_1_2_0 = (CrossReference)cIncomingAssignment_1_2.eContents().get(0);
		private final RuleCall cIncomingXCableIDTerminalRuleCall_1_2_0_1 = (RuleCall)cIncomingXCableCrossReference_1_2_0.eContents().get(1);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cCommaKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cIncomingAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final CrossReference cIncomingXCableCrossReference_1_3_1_0 = (CrossReference)cIncomingAssignment_1_3_1.eContents().get(0);
		private final RuleCall cIncomingXCableIDTerminalRuleCall_1_3_1_0_1 = (RuleCall)cIncomingXCableCrossReference_1_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_4 = (Keyword)cGroup_1.eContents().get(4);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cOutgoingKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cOutgoingAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final CrossReference cOutgoingXCableCrossReference_2_2_0 = (CrossReference)cOutgoingAssignment_2_2.eContents().get(0);
		private final RuleCall cOutgoingXCableIDTerminalRuleCall_2_2_0_1 = (RuleCall)cOutgoingXCableCrossReference_2_2_0.eContents().get(1);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cOutgoingAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final CrossReference cOutgoingXCableCrossReference_2_3_1_0 = (CrossReference)cOutgoingAssignment_2_3_1.eContents().get(0);
		private final RuleCall cOutgoingXCableIDTerminalRuleCall_2_3_1_0_1 = (RuleCall)cOutgoingXCableCrossReference_2_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		
		//Connections:
		//	{Connections} ('incoming' '(' incoming+=[XCable] ("," incoming+=[XCable])* ')')? ('outgoing' '(' outgoing+=[XCable]
		//	("," outgoing+=[XCable])* ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Connections} ('incoming' '(' incoming+=[XCable] ("," incoming+=[XCable])* ')')? ('outgoing' '(' outgoing+=[XCable] (","
		//outgoing+=[XCable])* ')')?
		public Group getGroup() { return cGroup; }
		
		//{Connections}
		public Action getConnectionsAction_0() { return cConnectionsAction_0; }
		
		//('incoming' '(' incoming+=[XCable] ("," incoming+=[XCable])* ')')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'incoming'
		public Keyword getIncomingKeyword_1_0() { return cIncomingKeyword_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_1() { return cLeftParenthesisKeyword_1_1; }
		
		//incoming+=[XCable]
		public Assignment getIncomingAssignment_1_2() { return cIncomingAssignment_1_2; }
		
		//[XCable]
		public CrossReference getIncomingXCableCrossReference_1_2_0() { return cIncomingXCableCrossReference_1_2_0; }
		
		//ID
		public RuleCall getIncomingXCableIDTerminalRuleCall_1_2_0_1() { return cIncomingXCableIDTerminalRuleCall_1_2_0_1; }
		
		//("," incoming+=[XCable])*
		public Group getGroup_1_3() { return cGroup_1_3; }
		
		//","
		public Keyword getCommaKeyword_1_3_0() { return cCommaKeyword_1_3_0; }
		
		//incoming+=[XCable]
		public Assignment getIncomingAssignment_1_3_1() { return cIncomingAssignment_1_3_1; }
		
		//[XCable]
		public CrossReference getIncomingXCableCrossReference_1_3_1_0() { return cIncomingXCableCrossReference_1_3_1_0; }
		
		//ID
		public RuleCall getIncomingXCableIDTerminalRuleCall_1_3_1_0_1() { return cIncomingXCableIDTerminalRuleCall_1_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_4() { return cRightParenthesisKeyword_1_4; }
		
		//('outgoing' '(' outgoing+=[XCable] ("," outgoing+=[XCable])* ')')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'outgoing'
		public Keyword getOutgoingKeyword_2_0() { return cOutgoingKeyword_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1() { return cLeftParenthesisKeyword_2_1; }
		
		//outgoing+=[XCable]
		public Assignment getOutgoingAssignment_2_2() { return cOutgoingAssignment_2_2; }
		
		//[XCable]
		public CrossReference getOutgoingXCableCrossReference_2_2_0() { return cOutgoingXCableCrossReference_2_2_0; }
		
		//ID
		public RuleCall getOutgoingXCableIDTerminalRuleCall_2_2_0_1() { return cOutgoingXCableIDTerminalRuleCall_2_2_0_1; }
		
		//("," outgoing+=[XCable])*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//","
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//outgoing+=[XCable]
		public Assignment getOutgoingAssignment_2_3_1() { return cOutgoingAssignment_2_3_1; }
		
		//[XCable]
		public CrossReference getOutgoingXCableCrossReference_2_3_1_0() { return cOutgoingXCableCrossReference_2_3_1_0; }
		
		//ID
		public RuleCall getOutgoingXCableIDTerminalRuleCall_2_3_1_0_1() { return cOutgoingXCableIDTerminalRuleCall_2_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_4() { return cRightParenthesisKeyword_2_4; }
	}
	public class EBigIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.EBigInteger");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EBigInteger ecore::EBigInteger:
		//	INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class BoolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.bool");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//bool ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class CableAttributesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.CableAttributes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCableAttributesAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSpeedKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSpeedAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSpeedEBigIntegerParserRuleCall_2_0 = (RuleCall)cSpeedAssignment_2.eContents().get(0);
		private final Keyword cEndPoint1Keyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEndPoint1Assignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cEndPoint1XDeviceCrossReference_4_0 = (CrossReference)cEndPoint1Assignment_4.eContents().get(0);
		private final RuleCall cEndPoint1XDeviceIDTerminalRuleCall_4_0_1 = (RuleCall)cEndPoint1XDeviceCrossReference_4_0.eContents().get(1);
		private final Keyword cEndPoint2Keyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEndPoint2Assignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cEndPoint2XDeviceCrossReference_6_0 = (CrossReference)cEndPoint2Assignment_6.eContents().get(0);
		private final RuleCall cEndPoint2XDeviceIDTerminalRuleCall_6_0_1 = (RuleCall)cEndPoint2XDeviceCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cIsDuplexKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIsDuplexAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cIsDuplexBoolParserRuleCall_7_1_0 = (RuleCall)cIsDuplexAssignment_7_1.eContents().get(0);
		
		//CableAttributes:
		//	{CableAttributes}
		//	'speed' speed=EBigInteger
		//	'endPoint1' endPoint1=[XDevice]
		//	'endPoint2' endPoint2=[XDevice] ('isDuplex' isDuplex=bool)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{CableAttributes} 'speed' speed=EBigInteger 'endPoint1' endPoint1=[XDevice] 'endPoint2' endPoint2=[XDevice] ('isDuplex'
		//isDuplex=bool)?
		public Group getGroup() { return cGroup; }
		
		//{CableAttributes}
		public Action getCableAttributesAction_0() { return cCableAttributesAction_0; }
		
		//'speed'
		public Keyword getSpeedKeyword_1() { return cSpeedKeyword_1; }
		
		//speed=EBigInteger
		public Assignment getSpeedAssignment_2() { return cSpeedAssignment_2; }
		
		//EBigInteger
		public RuleCall getSpeedEBigIntegerParserRuleCall_2_0() { return cSpeedEBigIntegerParserRuleCall_2_0; }
		
		//'endPoint1'
		public Keyword getEndPoint1Keyword_3() { return cEndPoint1Keyword_3; }
		
		//endPoint1=[XDevice]
		public Assignment getEndPoint1Assignment_4() { return cEndPoint1Assignment_4; }
		
		//[XDevice]
		public CrossReference getEndPoint1XDeviceCrossReference_4_0() { return cEndPoint1XDeviceCrossReference_4_0; }
		
		//ID
		public RuleCall getEndPoint1XDeviceIDTerminalRuleCall_4_0_1() { return cEndPoint1XDeviceIDTerminalRuleCall_4_0_1; }
		
		//'endPoint2'
		public Keyword getEndPoint2Keyword_5() { return cEndPoint2Keyword_5; }
		
		//endPoint2=[XDevice]
		public Assignment getEndPoint2Assignment_6() { return cEndPoint2Assignment_6; }
		
		//[XDevice]
		public CrossReference getEndPoint2XDeviceCrossReference_6_0() { return cEndPoint2XDeviceCrossReference_6_0; }
		
		//ID
		public RuleCall getEndPoint2XDeviceIDTerminalRuleCall_6_0_1() { return cEndPoint2XDeviceIDTerminalRuleCall_6_0_1; }
		
		//('isDuplex' isDuplex=bool)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'isDuplex'
		public Keyword getIsDuplexKeyword_7_0() { return cIsDuplexKeyword_7_0; }
		
		//isDuplex=bool
		public Assignment getIsDuplexAssignment_7_1() { return cIsDuplexAssignment_7_1; }
		
		//bool
		public RuleCall getIsDuplexBoolParserRuleCall_7_1_0() { return cIsDuplexBoolParserRuleCall_7_1_0; }
	}
	public class XServerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.XServer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMaxSlotsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMaxSlotsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMaxSlotsEBigIntegerParserRuleCall_4_0 = (RuleCall)cMaxSlotsAssignment_4.eContents().get(0);
		private final Keyword cMTBFKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMTBFAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMTBFEBigIntegerParserRuleCall_6_0 = (RuleCall)cMTBFAssignment_6.eContents().get(0);
		private final Assignment cConnectionsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cConnectionsConnectionsParserRuleCall_7_0 = (RuleCall)cConnectionsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//XServer:
		//	'Server'
		//	name=ID
		//	'{'
		//	'maxSlots' maxSlots=EBigInteger
		//	'MTBF' MTBF=EBigInteger
		//	connections=Connections '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Server' name=ID '{' 'maxSlots' maxSlots=EBigInteger 'MTBF' MTBF=EBigInteger connections=Connections '}'
		public Group getGroup() { return cGroup; }
		
		//'Server'
		public Keyword getServerKeyword_0() { return cServerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'maxSlots'
		public Keyword getMaxSlotsKeyword_3() { return cMaxSlotsKeyword_3; }
		
		//maxSlots=EBigInteger
		public Assignment getMaxSlotsAssignment_4() { return cMaxSlotsAssignment_4; }
		
		//EBigInteger
		public RuleCall getMaxSlotsEBigIntegerParserRuleCall_4_0() { return cMaxSlotsEBigIntegerParserRuleCall_4_0; }
		
		//'MTBF'
		public Keyword getMTBFKeyword_5() { return cMTBFKeyword_5; }
		
		//MTBF=EBigInteger
		public Assignment getMTBFAssignment_6() { return cMTBFAssignment_6; }
		
		//EBigInteger
		public RuleCall getMTBFEBigIntegerParserRuleCall_6_0() { return cMTBFEBigIntegerParserRuleCall_6_0; }
		
		//connections=Connections
		public Assignment getConnectionsAssignment_7() { return cConnectionsAssignment_7; }
		
		//Connections
		public RuleCall getConnectionsConnectionsParserRuleCall_7_0() { return cConnectionsConnectionsParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class XComputerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.XComputer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComputerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConnectionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConnectionsConnectionsParserRuleCall_3_0 = (RuleCall)cConnectionsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//XComputer:
		//	'Computer'
		//	name=ID
		//	'{'
		//	connections=Connections '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Computer' name=ID '{' connections=Connections '}'
		public Group getGroup() { return cGroup; }
		
		//'Computer'
		public Keyword getComputerKeyword_0() { return cComputerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//connections=Connections
		public Assignment getConnectionsAssignment_3() { return cConnectionsAssignment_3; }
		
		//Connections
		public RuleCall getConnectionsConnectionsParserRuleCall_3_0() { return cConnectionsConnectionsParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class XRouterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.XRouter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRouterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMaxSpeedKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMaxSpeedAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMaxSpeedEBigIntegerParserRuleCall_4_0 = (RuleCall)cMaxSpeedAssignment_4.eContents().get(0);
		private final Assignment cConnectionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cConnectionsConnectionsParserRuleCall_5_0 = (RuleCall)cConnectionsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//XRouter:
		//	'Router'
		//	name=ID
		//	'{'
		//	'maxSpeed' maxSpeed=EBigInteger
		//	connections=Connections '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Router' name=ID '{' 'maxSpeed' maxSpeed=EBigInteger connections=Connections '}'
		public Group getGroup() { return cGroup; }
		
		//'Router'
		public Keyword getRouterKeyword_0() { return cRouterKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'maxSpeed'
		public Keyword getMaxSpeedKeyword_3() { return cMaxSpeedKeyword_3; }
		
		//maxSpeed=EBigInteger
		public Assignment getMaxSpeedAssignment_4() { return cMaxSpeedAssignment_4; }
		
		//EBigInteger
		public RuleCall getMaxSpeedEBigIntegerParserRuleCall_4_0() { return cMaxSpeedEBigIntegerParserRuleCall_4_0; }
		
		//connections=Connections
		public Assignment getConnectionsAssignment_5() { return cConnectionsAssignment_5; }
		
		//Connections
		public RuleCall getConnectionsConnectionsParserRuleCall_5_0() { return cConnectionsConnectionsParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class XCopperCableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.XCopperCable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCopperCableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCableAttributesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCableAttributesCableAttributesParserRuleCall_3_0 = (RuleCall)cCableAttributesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//XCopperCable:
		//	'CopperCable'
		//	name=ID
		//	'{'
		//	cableAttributes=CableAttributes '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'CopperCable' name=ID '{' cableAttributes=CableAttributes '}'
		public Group getGroup() { return cGroup; }
		
		//'CopperCable'
		public Keyword getCopperCableKeyword_0() { return cCopperCableKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//cableAttributes=CableAttributes
		public Assignment getCableAttributesAssignment_3() { return cCableAttributesAssignment_3; }
		
		//CableAttributes
		public RuleCall getCableAttributesCableAttributesParserRuleCall_3_0() { return cCableAttributesCableAttributesParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class XGlassFiberCableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtextImplementation.XtextImpl.XGlassFiberCable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGlassFiberCableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCableAttributesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCableAttributesCableAttributesParserRuleCall_3_0 = (RuleCall)cCableAttributesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//XGlassFiberCable:
		//	'GlassFiberCable'
		//	name=ID
		//	'{'
		//	cableAttributes=CableAttributes '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GlassFiberCable' name=ID '{' cableAttributes=CableAttributes '}'
		public Group getGroup() { return cGroup; }
		
		//'GlassFiberCable'
		public Keyword getGlassFiberCableKeyword_0() { return cGlassFiberCableKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//cableAttributes=CableAttributes
		public Assignment getCableAttributesAssignment_3() { return cCableAttributesAssignment_3; }
		
		//CableAttributes
		public RuleCall getCableAttributesCableAttributesParserRuleCall_3_0() { return cCableAttributesCableAttributesParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private final XContainerElements pXContainer;
	private final NetworkElementElements pNetworkElement;
	private final XDeviceElements pXDevice;
	private final XCableElements pXCable;
	private final ConnectionsElements pConnections;
	private final EBigIntegerElements pEBigInteger;
	private final BoolElements pBool;
	private final CableAttributesElements pCableAttributes;
	private final XServerElements pXServer;
	private final XComputerElements pXComputer;
	private final XRouterElements pXRouter;
	private final XCopperCableElements pXCopperCable;
	private final XGlassFiberCableElements pXGlassFiberCable;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public XtextImplGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pXContainer = new XContainerElements();
		this.pNetworkElement = new NetworkElementElements();
		this.pXDevice = new XDeviceElements();
		this.pXCable = new XCableElements();
		this.pConnections = new ConnectionsElements();
		this.pEBigInteger = new EBigIntegerElements();
		this.pBool = new BoolElements();
		this.pCableAttributes = new CableAttributesElements();
		this.pXServer = new XServerElements();
		this.pXComputer = new XComputerElements();
		this.pXRouter = new XRouterElements();
		this.pXCopperCable = new XCopperCableElements();
		this.pXGlassFiberCable = new XGlassFiberCableElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("xtextImplementation.XtextImpl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//XContainer:
	//	elements+=NetworkElement*;
	public XContainerElements getXContainerAccess() {
		return pXContainer;
	}
	
	public ParserRule getXContainerRule() {
		return getXContainerAccess().getRule();
	}
	
	//NetworkElement NetworkElements:
	//	XDevice | XCable;
	public NetworkElementElements getNetworkElementAccess() {
		return pNetworkElement;
	}
	
	public ParserRule getNetworkElementRule() {
		return getNetworkElementAccess().getRule();
	}
	
	//XDevice:
	//	XServer | XComputer | XRouter;
	public XDeviceElements getXDeviceAccess() {
		return pXDevice;
	}
	
	public ParserRule getXDeviceRule() {
		return getXDeviceAccess().getRule();
	}
	
	//XCable:
	//	XCopperCable | XGlassFiberCable;
	public XCableElements getXCableAccess() {
		return pXCable;
	}
	
	public ParserRule getXCableRule() {
		return getXCableAccess().getRule();
	}
	
	//Connections:
	//	{Connections} ('incoming' '(' incoming+=[XCable] ("," incoming+=[XCable])* ')')? ('outgoing' '(' outgoing+=[XCable]
	//	("," outgoing+=[XCable])* ')')?;
	public ConnectionsElements getConnectionsAccess() {
		return pConnections;
	}
	
	public ParserRule getConnectionsRule() {
		return getConnectionsAccess().getRule();
	}
	
	//EBigInteger ecore::EBigInteger:
	//	INT;
	public EBigIntegerElements getEBigIntegerAccess() {
		return pEBigInteger;
	}
	
	public ParserRule getEBigIntegerRule() {
		return getEBigIntegerAccess().getRule();
	}
	
	//bool ecore::EBoolean:
	//	'true' | 'false';
	public BoolElements getBoolAccess() {
		return pBool;
	}
	
	public ParserRule getBoolRule() {
		return getBoolAccess().getRule();
	}
	
	//CableAttributes:
	//	{CableAttributes}
	//	'speed' speed=EBigInteger
	//	'endPoint1' endPoint1=[XDevice]
	//	'endPoint2' endPoint2=[XDevice] ('isDuplex' isDuplex=bool)?;
	public CableAttributesElements getCableAttributesAccess() {
		return pCableAttributes;
	}
	
	public ParserRule getCableAttributesRule() {
		return getCableAttributesAccess().getRule();
	}
	
	//XServer:
	//	'Server'
	//	name=ID
	//	'{'
	//	'maxSlots' maxSlots=EBigInteger
	//	'MTBF' MTBF=EBigInteger
	//	connections=Connections '}';
	public XServerElements getXServerAccess() {
		return pXServer;
	}
	
	public ParserRule getXServerRule() {
		return getXServerAccess().getRule();
	}
	
	//XComputer:
	//	'Computer'
	//	name=ID
	//	'{'
	//	connections=Connections '}';
	public XComputerElements getXComputerAccess() {
		return pXComputer;
	}
	
	public ParserRule getXComputerRule() {
		return getXComputerAccess().getRule();
	}
	
	//XRouter:
	//	'Router'
	//	name=ID
	//	'{'
	//	'maxSpeed' maxSpeed=EBigInteger
	//	connections=Connections '}';
	public XRouterElements getXRouterAccess() {
		return pXRouter;
	}
	
	public ParserRule getXRouterRule() {
		return getXRouterAccess().getRule();
	}
	
	//XCopperCable:
	//	'CopperCable'
	//	name=ID
	//	'{'
	//	cableAttributes=CableAttributes '}';
	public XCopperCableElements getXCopperCableAccess() {
		return pXCopperCable;
	}
	
	public ParserRule getXCopperCableRule() {
		return getXCopperCableAccess().getRule();
	}
	
	//XGlassFiberCable:
	//	'GlassFiberCable'
	//	name=ID
	//	'{'
	//	cableAttributes=CableAttributes '}';
	public XGlassFiberCableElements getXGlassFiberCableAccess() {
		return pXGlassFiberCable;
	}
	
	public ParserRule getXGlassFiberCableRule() {
		return getXGlassFiberCableAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
