/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import xtextImplementation.xtextImpl.Connections;
import xtextImplementation.xtextImpl.XCable;
import xtextImplementation.xtextImpl.XtextImplPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Connections</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.impl.ConnectionsImpl#getIncoming <em>Incoming</em>}</li>
 *   <li>{@link xtextImplementation.xtextImpl.impl.ConnectionsImpl#getOutgoing <em>Outgoing</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConnectionsImpl extends MinimalEObjectImpl.Container implements Connections
{
  /**
   * The cached value of the '{@link #getIncoming() <em>Incoming</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIncoming()
   * @generated
   * @ordered
   */
  protected EList<XCable> incoming;

  /**
   * The cached value of the '{@link #getOutgoing() <em>Outgoing</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOutgoing()
   * @generated
   * @ordered
   */
  protected EList<XCable> outgoing;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnectionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XtextImplPackage.Literals.CONNECTIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<XCable> getIncoming()
  {
    if (incoming == null)
    {
      incoming = new EObjectResolvingEList<XCable>(XCable.class, this, XtextImplPackage.CONNECTIONS__INCOMING);
    }
    return incoming;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<XCable> getOutgoing()
  {
    if (outgoing == null)
    {
      outgoing = new EObjectResolvingEList<XCable>(XCable.class, this, XtextImplPackage.CONNECTIONS__OUTGOING);
    }
    return outgoing;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XtextImplPackage.CONNECTIONS__INCOMING:
        return getIncoming();
      case XtextImplPackage.CONNECTIONS__OUTGOING:
        return getOutgoing();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XtextImplPackage.CONNECTIONS__INCOMING:
        getIncoming().clear();
        getIncoming().addAll((Collection<? extends XCable>)newValue);
        return;
      case XtextImplPackage.CONNECTIONS__OUTGOING:
        getOutgoing().clear();
        getOutgoing().addAll((Collection<? extends XCable>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XtextImplPackage.CONNECTIONS__INCOMING:
        getIncoming().clear();
        return;
      case XtextImplPackage.CONNECTIONS__OUTGOING:
        getOutgoing().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XtextImplPackage.CONNECTIONS__INCOMING:
        return incoming != null && !incoming.isEmpty();
      case XtextImplPackage.CONNECTIONS__OUTGOING:
        return outgoing != null && !outgoing.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ConnectionsImpl
