/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtextImplementation.xtextImpl.CableAttributes;
import xtextImplementation.xtextImpl.XCable;
import xtextImplementation.xtextImpl.XtextImplPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XCable</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.impl.XCableImpl#getCableAttributes <em>Cable Attributes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class XCableImpl extends NetworkElementsImpl implements XCable
{
  /**
   * The cached value of the '{@link #getCableAttributes() <em>Cable Attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCableAttributes()
   * @generated
   * @ordered
   */
  protected CableAttributes cableAttributes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XCableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XtextImplPackage.Literals.XCABLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CableAttributes getCableAttributes()
  {
    return cableAttributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCableAttributes(CableAttributes newCableAttributes, NotificationChain msgs)
  {
    CableAttributes oldCableAttributes = cableAttributes;
    cableAttributes = newCableAttributes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, XtextImplPackage.XCABLE__CABLE_ATTRIBUTES, oldCableAttributes, newCableAttributes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCableAttributes(CableAttributes newCableAttributes)
  {
    if (newCableAttributes != cableAttributes)
    {
      NotificationChain msgs = null;
      if (cableAttributes != null)
        msgs = ((InternalEObject)cableAttributes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - XtextImplPackage.XCABLE__CABLE_ATTRIBUTES, null, msgs);
      if (newCableAttributes != null)
        msgs = ((InternalEObject)newCableAttributes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - XtextImplPackage.XCABLE__CABLE_ATTRIBUTES, null, msgs);
      msgs = basicSetCableAttributes(newCableAttributes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XtextImplPackage.XCABLE__CABLE_ATTRIBUTES, newCableAttributes, newCableAttributes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case XtextImplPackage.XCABLE__CABLE_ATTRIBUTES:
        return basicSetCableAttributes(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XtextImplPackage.XCABLE__CABLE_ATTRIBUTES:
        return getCableAttributes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XtextImplPackage.XCABLE__CABLE_ATTRIBUTES:
        setCableAttributes((CableAttributes)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XtextImplPackage.XCABLE__CABLE_ATTRIBUTES:
        setCableAttributes((CableAttributes)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XtextImplPackage.XCABLE__CABLE_ATTRIBUTES:
        return cableAttributes != null;
    }
    return super.eIsSet(featureID);
  }

} //XCableImpl
