/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.impl;

import org.eclipse.emf.ecore.EClass;

import xtextImplementation.xtextImpl.XComputer;
import xtextImplementation.xtextImpl.XtextImplPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XComputer</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XComputerImpl extends XDeviceImpl implements XComputer
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XComputerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XtextImplPackage.Literals.XCOMPUTER;
  }

} //XComputerImpl
