/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.impl;

import org.eclipse.emf.ecore.EClass;

import xtextImplementation.xtextImpl.XCopperCable;
import xtextImplementation.xtextImpl.XtextImplPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XCopper Cable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XCopperCableImpl extends XCableImpl implements XCopperCable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XCopperCableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XtextImplPackage.Literals.XCOPPER_CABLE;
  }

} //XCopperCableImpl
