/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.impl;

import org.eclipse.emf.ecore.EClass;

import xtextImplementation.xtextImpl.XGlassFiberCable;
import xtextImplementation.xtextImpl.XtextImplPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XGlass Fiber Cable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XGlassFiberCableImpl extends XCableImpl implements XGlassFiberCable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XGlassFiberCableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XtextImplPackage.Literals.XGLASS_FIBER_CABLE;
  }

} //XGlassFiberCableImpl
