/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.impl;

import java.math.BigInteger;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtextImplementation.xtextImpl.XRouter;
import xtextImplementation.xtextImpl.XtextImplPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XRouter</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.impl.XRouterImpl#getMaxSpeed <em>Max Speed</em>}</li>
 * </ul>
 *
 * @generated
 */
public class XRouterImpl extends XDeviceImpl implements XRouter
{
  /**
   * The default value of the '{@link #getMaxSpeed() <em>Max Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxSpeed()
   * @generated
   * @ordered
   */
  protected static final BigInteger MAX_SPEED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMaxSpeed() <em>Max Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxSpeed()
   * @generated
   * @ordered
   */
  protected BigInteger maxSpeed = MAX_SPEED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XRouterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XtextImplPackage.Literals.XROUTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BigInteger getMaxSpeed()
  {
    return maxSpeed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMaxSpeed(BigInteger newMaxSpeed)
  {
    BigInteger oldMaxSpeed = maxSpeed;
    maxSpeed = newMaxSpeed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XtextImplPackage.XROUTER__MAX_SPEED, oldMaxSpeed, maxSpeed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XtextImplPackage.XROUTER__MAX_SPEED:
        return getMaxSpeed();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XtextImplPackage.XROUTER__MAX_SPEED:
        setMaxSpeed((BigInteger)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XtextImplPackage.XROUTER__MAX_SPEED:
        setMaxSpeed(MAX_SPEED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XtextImplPackage.XROUTER__MAX_SPEED:
        return MAX_SPEED_EDEFAULT == null ? maxSpeed != null : !MAX_SPEED_EDEFAULT.equals(maxSpeed);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (maxSpeed: ");
    result.append(maxSpeed);
    result.append(')');
    return result.toString();
  }

} //XRouterImpl
