/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.impl;

import java.math.BigInteger;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import xtextImplementation.xtextImpl.XServer;
import xtextImplementation.xtextImpl.XtextImplPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>XServer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.impl.XServerImpl#getMaxSlots <em>Max Slots</em>}</li>
 *   <li>{@link xtextImplementation.xtextImpl.impl.XServerImpl#getMTBF <em>MTBF</em>}</li>
 * </ul>
 *
 * @generated
 */
public class XServerImpl extends XDeviceImpl implements XServer
{
  /**
   * The default value of the '{@link #getMaxSlots() <em>Max Slots</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxSlots()
   * @generated
   * @ordered
   */
  protected static final BigInteger MAX_SLOTS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMaxSlots() <em>Max Slots</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxSlots()
   * @generated
   * @ordered
   */
  protected BigInteger maxSlots = MAX_SLOTS_EDEFAULT;

  /**
   * The default value of the '{@link #getMTBF() <em>MTBF</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMTBF()
   * @generated
   * @ordered
   */
  protected static final BigInteger MTBF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMTBF() <em>MTBF</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMTBF()
   * @generated
   * @ordered
   */
  protected BigInteger mtbf = MTBF_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XServerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XtextImplPackage.Literals.XSERVER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BigInteger getMaxSlots()
  {
    return maxSlots;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMaxSlots(BigInteger newMaxSlots)
  {
    BigInteger oldMaxSlots = maxSlots;
    maxSlots = newMaxSlots;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XtextImplPackage.XSERVER__MAX_SLOTS, oldMaxSlots, maxSlots));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BigInteger getMTBF()
  {
    return mtbf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMTBF(BigInteger newMTBF)
  {
    BigInteger oldMTBF = mtbf;
    mtbf = newMTBF;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, XtextImplPackage.XSERVER__MTBF, oldMTBF, mtbf));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case XtextImplPackage.XSERVER__MAX_SLOTS:
        return getMaxSlots();
      case XtextImplPackage.XSERVER__MTBF:
        return getMTBF();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case XtextImplPackage.XSERVER__MAX_SLOTS:
        setMaxSlots((BigInteger)newValue);
        return;
      case XtextImplPackage.XSERVER__MTBF:
        setMTBF((BigInteger)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case XtextImplPackage.XSERVER__MAX_SLOTS:
        setMaxSlots(MAX_SLOTS_EDEFAULT);
        return;
      case XtextImplPackage.XSERVER__MTBF:
        setMTBF(MTBF_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case XtextImplPackage.XSERVER__MAX_SLOTS:
        return MAX_SLOTS_EDEFAULT == null ? maxSlots != null : !MAX_SLOTS_EDEFAULT.equals(maxSlots);
      case XtextImplPackage.XSERVER__MTBF:
        return MTBF_EDEFAULT == null ? mtbf != null : !MTBF_EDEFAULT.equals(mtbf);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (maxSlots: ");
    result.append(maxSlots);
    result.append(", MTBF: ");
    result.append(mtbf);
    result.append(')');
    return result.toString();
  }

} //XServerImpl
