/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import xtextImplementation.xtextImpl.CableAttributes;
import xtextImplementation.xtextImpl.Connections;
import xtextImplementation.xtextImpl.NetworkElements;
import xtextImplementation.xtextImpl.XCable;
import xtextImplementation.xtextImpl.XComputer;
import xtextImplementation.xtextImpl.XContainer;
import xtextImplementation.xtextImpl.XCopperCable;
import xtextImplementation.xtextImpl.XDevice;
import xtextImplementation.xtextImpl.XGlassFiberCable;
import xtextImplementation.xtextImpl.XRouter;
import xtextImplementation.xtextImpl.XServer;
import xtextImplementation.xtextImpl.XtextImplFactory;
import xtextImplementation.xtextImpl.XtextImplPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class XtextImplPackageImpl extends EPackageImpl implements XtextImplPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xContainerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass networkElementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xDeviceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xCableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass connectionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cableAttributesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xServerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xComputerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xRouterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xCopperCableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xGlassFiberCableEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see xtextImplementation.xtextImpl.XtextImplPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private XtextImplPackageImpl()
  {
    super(eNS_URI, XtextImplFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link XtextImplPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static XtextImplPackage init()
  {
    if (isInited) return (XtextImplPackage)EPackage.Registry.INSTANCE.getEPackage(XtextImplPackage.eNS_URI);

    // Obtain or create and register package
    XtextImplPackageImpl theXtextImplPackage = (XtextImplPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof XtextImplPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new XtextImplPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theXtextImplPackage.createPackageContents();

    // Initialize created meta-data
    theXtextImplPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theXtextImplPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(XtextImplPackage.eNS_URI, theXtextImplPackage);
    return theXtextImplPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXContainer()
  {
    return xContainerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getXContainer_Elements()
  {
    return (EReference)xContainerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getNetworkElements()
  {
    return networkElementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getNetworkElements_Name()
  {
    return (EAttribute)networkElementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXDevice()
  {
    return xDeviceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getXDevice_Connections()
  {
    return (EReference)xDeviceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXCable()
  {
    return xCableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getXCable_CableAttributes()
  {
    return (EReference)xCableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConnections()
  {
    return connectionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConnections_Incoming()
  {
    return (EReference)connectionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConnections_Outgoing()
  {
    return (EReference)connectionsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCableAttributes()
  {
    return cableAttributesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCableAttributes_Speed()
  {
    return (EAttribute)cableAttributesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCableAttributes_EndPoint1()
  {
    return (EReference)cableAttributesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCableAttributes_EndPoint2()
  {
    return (EReference)cableAttributesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCableAttributes_IsDuplex()
  {
    return (EAttribute)cableAttributesEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXServer()
  {
    return xServerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getXServer_MaxSlots()
  {
    return (EAttribute)xServerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getXServer_MTBF()
  {
    return (EAttribute)xServerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXComputer()
  {
    return xComputerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXRouter()
  {
    return xRouterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getXRouter_MaxSpeed()
  {
    return (EAttribute)xRouterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXCopperCable()
  {
    return xCopperCableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getXGlassFiberCable()
  {
    return xGlassFiberCableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XtextImplFactory getXtextImplFactory()
  {
    return (XtextImplFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    xContainerEClass = createEClass(XCONTAINER);
    createEReference(xContainerEClass, XCONTAINER__ELEMENTS);

    networkElementsEClass = createEClass(NETWORK_ELEMENTS);
    createEAttribute(networkElementsEClass, NETWORK_ELEMENTS__NAME);

    xDeviceEClass = createEClass(XDEVICE);
    createEReference(xDeviceEClass, XDEVICE__CONNECTIONS);

    xCableEClass = createEClass(XCABLE);
    createEReference(xCableEClass, XCABLE__CABLE_ATTRIBUTES);

    connectionsEClass = createEClass(CONNECTIONS);
    createEReference(connectionsEClass, CONNECTIONS__INCOMING);
    createEReference(connectionsEClass, CONNECTIONS__OUTGOING);

    cableAttributesEClass = createEClass(CABLE_ATTRIBUTES);
    createEAttribute(cableAttributesEClass, CABLE_ATTRIBUTES__SPEED);
    createEReference(cableAttributesEClass, CABLE_ATTRIBUTES__END_POINT1);
    createEReference(cableAttributesEClass, CABLE_ATTRIBUTES__END_POINT2);
    createEAttribute(cableAttributesEClass, CABLE_ATTRIBUTES__IS_DUPLEX);

    xServerEClass = createEClass(XSERVER);
    createEAttribute(xServerEClass, XSERVER__MAX_SLOTS);
    createEAttribute(xServerEClass, XSERVER__MTBF);

    xComputerEClass = createEClass(XCOMPUTER);

    xRouterEClass = createEClass(XROUTER);
    createEAttribute(xRouterEClass, XROUTER__MAX_SPEED);

    xCopperCableEClass = createEClass(XCOPPER_CABLE);

    xGlassFiberCableEClass = createEClass(XGLASS_FIBER_CABLE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    xDeviceEClass.getESuperTypes().add(this.getNetworkElements());
    xCableEClass.getESuperTypes().add(this.getNetworkElements());
    xServerEClass.getESuperTypes().add(this.getXDevice());
    xComputerEClass.getESuperTypes().add(this.getXDevice());
    xRouterEClass.getESuperTypes().add(this.getXDevice());
    xCopperCableEClass.getESuperTypes().add(this.getXCable());
    xGlassFiberCableEClass.getESuperTypes().add(this.getXCable());

    // Initialize classes and features; add operations and parameters
    initEClass(xContainerEClass, XContainer.class, "XContainer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXContainer_Elements(), this.getNetworkElements(), null, "elements", null, 0, -1, XContainer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(networkElementsEClass, NetworkElements.class, "NetworkElements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNetworkElements_Name(), ecorePackage.getEString(), "name", null, 0, 1, NetworkElements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xDeviceEClass, XDevice.class, "XDevice", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXDevice_Connections(), this.getConnections(), null, "connections", null, 0, 1, XDevice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xCableEClass, XCable.class, "XCable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXCable_CableAttributes(), this.getCableAttributes(), null, "cableAttributes", null, 0, 1, XCable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(connectionsEClass, Connections.class, "Connections", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getConnections_Incoming(), this.getXCable(), null, "incoming", null, 0, -1, Connections.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConnections_Outgoing(), this.getXCable(), null, "outgoing", null, 0, -1, Connections.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(cableAttributesEClass, CableAttributes.class, "CableAttributes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCableAttributes_Speed(), ecorePackage.getEBigInteger(), "speed", null, 0, 1, CableAttributes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCableAttributes_EndPoint1(), this.getXDevice(), null, "endPoint1", null, 0, 1, CableAttributes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCableAttributes_EndPoint2(), this.getXDevice(), null, "endPoint2", null, 0, 1, CableAttributes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCableAttributes_IsDuplex(), ecorePackage.getEBoolean(), "isDuplex", null, 0, 1, CableAttributes.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xServerEClass, XServer.class, "XServer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXServer_MaxSlots(), ecorePackage.getEBigInteger(), "maxSlots", null, 0, 1, XServer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getXServer_MTBF(), ecorePackage.getEBigInteger(), "MTBF", null, 0, 1, XServer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xComputerEClass, XComputer.class, "XComputer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(xRouterEClass, XRouter.class, "XRouter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getXRouter_MaxSpeed(), ecorePackage.getEBigInteger(), "maxSpeed", null, 0, 1, XRouter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xCopperCableEClass, XCopperCable.class, "XCopperCable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(xGlassFiberCableEClass, XGlassFiberCable.class, "XGlassFiberCable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Create resource
    createResource(eNS_URI);
  }

} //XtextImplPackageImpl
