/**
 * generated by Xtext 2.10.0
 */
package requirementsXtext.validation;

import requirementsXtext.validation.AbstractReqXtextValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ReqXtextValidator extends AbstractReqXtextValidator {
}
