/**
 * generated by Xtext 2.12.0
 */
package xtextImplementation.ui.contentassist;

import xtextImplementation.ui.contentassist.AbstractXtextImplProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XtextImplProposalProvider extends AbstractXtextImplProposalProvider {
}
