/**
 * generated by Xtext 2.12.0
 */
package xtextImplementation.scoping;

import xtextImplementation.scoping.AbstractXtextImplScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class XtextImplScopeProvider extends AbstractXtextImplScopeProvider {
}
