/*
 * generated by Xtext 2.11.0
 */
package xtextImplementation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXtextImplScopeProvider extends DelegatingScopeProvider {
}
