/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see requirementsXtext.reqXtext.ReqXtextFactory
 * @model kind="package"
 * @generated
 */
public interface ReqXtextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "reqXtext";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "platform:/plugin/requirementsXtext/model/generated/ReqXtext.ecore";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "reqXtext";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReqXtextPackage eINSTANCE = requirementsXtext.reqXtext.impl.ReqXtextPackageImpl.init();

  /**
   * The meta object id for the '{@link requirementsXtext.reqXtext.impl.XContainerImpl <em>XContainer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see requirementsXtext.reqXtext.impl.XContainerImpl
   * @see requirementsXtext.reqXtext.impl.ReqXtextPackageImpl#getXContainer()
   * @generated
   */
  int XCONTAINER = 0;

  /**
   * The feature id for the '<em><b>Agents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCONTAINER__AGENTS = 0;

  /**
   * The number of structural features of the '<em>XContainer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCONTAINER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link requirementsXtext.reqXtext.impl.XAgentImpl <em>XAgent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see requirementsXtext.reqXtext.impl.XAgentImpl
   * @see requirementsXtext.reqXtext.impl.ReqXtextPackageImpl#getXAgent()
   * @generated
   */
  int XAGENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAGENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAGENT__SPEED = 1;

  /**
   * The number of structural features of the '<em>XAgent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XAGENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link requirementsXtext.reqXtext.impl.XProviderImpl <em>XProvider</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see requirementsXtext.reqXtext.impl.XProviderImpl
   * @see requirementsXtext.reqXtext.impl.ReqXtextPackageImpl#getXProvider()
   * @generated
   */
  int XPROVIDER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPROVIDER__NAME = XAGENT__NAME;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPROVIDER__SPEED = XAGENT__SPEED;

  /**
   * The number of structural features of the '<em>XProvider</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPROVIDER_FEATURE_COUNT = XAGENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link requirementsXtext.reqXtext.impl.XConsumerImpl <em>XConsumer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see requirementsXtext.reqXtext.impl.XConsumerImpl
   * @see requirementsXtext.reqXtext.impl.ReqXtextPackageImpl#getXConsumer()
   * @generated
   */
  int XCONSUMER = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCONSUMER__NAME = XAGENT__NAME;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCONSUMER__SPEED = XAGENT__SPEED;

  /**
   * The number of structural features of the '<em>XConsumer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCONSUMER_FEATURE_COUNT = XAGENT_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link requirementsXtext.reqXtext.XContainer <em>XContainer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XContainer</em>'.
   * @see requirementsXtext.reqXtext.XContainer
   * @generated
   */
  EClass getXContainer();

  /**
   * Returns the meta object for the containment reference list '{@link requirementsXtext.reqXtext.XContainer#getAgents <em>Agents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Agents</em>'.
   * @see requirementsXtext.reqXtext.XContainer#getAgents()
   * @see #getXContainer()
   * @generated
   */
  EReference getXContainer_Agents();

  /**
   * Returns the meta object for class '{@link requirementsXtext.reqXtext.XAgent <em>XAgent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XAgent</em>'.
   * @see requirementsXtext.reqXtext.XAgent
   * @generated
   */
  EClass getXAgent();

  /**
   * Returns the meta object for the attribute '{@link requirementsXtext.reqXtext.XAgent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see requirementsXtext.reqXtext.XAgent#getName()
   * @see #getXAgent()
   * @generated
   */
  EAttribute getXAgent_Name();

  /**
   * Returns the meta object for the attribute '{@link requirementsXtext.reqXtext.XAgent#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see requirementsXtext.reqXtext.XAgent#getSpeed()
   * @see #getXAgent()
   * @generated
   */
  EAttribute getXAgent_Speed();

  /**
   * Returns the meta object for class '{@link requirementsXtext.reqXtext.XProvider <em>XProvider</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XProvider</em>'.
   * @see requirementsXtext.reqXtext.XProvider
   * @generated
   */
  EClass getXProvider();

  /**
   * Returns the meta object for class '{@link requirementsXtext.reqXtext.XConsumer <em>XConsumer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XConsumer</em>'.
   * @see requirementsXtext.reqXtext.XConsumer
   * @generated
   */
  EClass getXConsumer();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ReqXtextFactory getReqXtextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link requirementsXtext.reqXtext.impl.XContainerImpl <em>XContainer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see requirementsXtext.reqXtext.impl.XContainerImpl
     * @see requirementsXtext.reqXtext.impl.ReqXtextPackageImpl#getXContainer()
     * @generated
     */
    EClass XCONTAINER = eINSTANCE.getXContainer();

    /**
     * The meta object literal for the '<em><b>Agents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCONTAINER__AGENTS = eINSTANCE.getXContainer_Agents();

    /**
     * The meta object literal for the '{@link requirementsXtext.reqXtext.impl.XAgentImpl <em>XAgent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see requirementsXtext.reqXtext.impl.XAgentImpl
     * @see requirementsXtext.reqXtext.impl.ReqXtextPackageImpl#getXAgent()
     * @generated
     */
    EClass XAGENT = eINSTANCE.getXAgent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XAGENT__NAME = eINSTANCE.getXAgent_Name();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XAGENT__SPEED = eINSTANCE.getXAgent_Speed();

    /**
     * The meta object literal for the '{@link requirementsXtext.reqXtext.impl.XProviderImpl <em>XProvider</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see requirementsXtext.reqXtext.impl.XProviderImpl
     * @see requirementsXtext.reqXtext.impl.ReqXtextPackageImpl#getXProvider()
     * @generated
     */
    EClass XPROVIDER = eINSTANCE.getXProvider();

    /**
     * The meta object literal for the '{@link requirementsXtext.reqXtext.impl.XConsumerImpl <em>XConsumer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see requirementsXtext.reqXtext.impl.XConsumerImpl
     * @see requirementsXtext.reqXtext.impl.ReqXtextPackageImpl#getXConsumer()
     * @generated
     */
    EClass XCONSUMER = eINSTANCE.getXConsumer();

  }

} //ReqXtextPackage
