/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see requirementsXtext.reqXtext.ReqXtextPackage
 * @generated
 */
public interface ReqXtextFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReqXtextFactory eINSTANCE = requirementsXtext.reqXtext.impl.ReqXtextFactoryImpl.init();

  /**
   * Returns a new object of class '<em>XContainer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XContainer</em>'.
   * @generated
   */
  XContainer createXContainer();

  /**
   * Returns a new object of class '<em>XAgent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XAgent</em>'.
   * @generated
   */
  XAgent createXAgent();

  /**
   * Returns a new object of class '<em>XProvider</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XProvider</em>'.
   * @generated
   */
  XProvider createXProvider();

  /**
   * Returns a new object of class '<em>XConsumer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XConsumer</em>'.
   * @generated
   */
  XConsumer createXConsumer();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ReqXtextPackage getReqXtextPackage();

} //ReqXtextFactory
