/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext;

import java.math.BigInteger;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XAgent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link requirementsXtext.reqXtext.XAgent#getName <em>Name</em>}</li>
 *   <li>{@link requirementsXtext.reqXtext.XAgent#getSpeed <em>Speed</em>}</li>
 * </ul>
 *
 * @see requirementsXtext.reqXtext.ReqXtextPackage#getXAgent()
 * @model
 * @generated
 */
public interface XAgent extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see requirementsXtext.reqXtext.ReqXtextPackage#getXAgent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link requirementsXtext.reqXtext.XAgent#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' attribute.
   * @see #setSpeed(BigInteger)
   * @see requirementsXtext.reqXtext.ReqXtextPackage#getXAgent_Speed()
   * @model
   * @generated
   */
  BigInteger getSpeed();

  /**
   * Sets the value of the '{@link requirementsXtext.reqXtext.XAgent#getSpeed <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' attribute.
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(BigInteger value);

} // XAgent
