/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XConsumer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see requirementsXtext.reqXtext.ReqXtextPackage#getXConsumer()
 * @model
 * @generated
 */
public interface XConsumer extends XAgent
{
} // XConsumer
