/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XContainer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link requirementsXtext.reqXtext.XContainer#getAgents <em>Agents</em>}</li>
 * </ul>
 *
 * @see requirementsXtext.reqXtext.ReqXtextPackage#getXContainer()
 * @model
 * @generated
 */
public interface XContainer extends EObject
{
  /**
   * Returns the value of the '<em><b>Agents</b></em>' containment reference list.
   * The list contents are of type {@link requirementsXtext.reqXtext.XAgent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agents</em>' containment reference list.
   * @see requirementsXtext.reqXtext.ReqXtextPackage#getXContainer_Agents()
   * @model containment="true"
   * @generated
   */
  EList<XAgent> getAgents();

} // XContainer
