/**
 * generated by Xtext 2.11.0
 */
package requirementsXtext.reqXtext;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XProvider</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see requirementsXtext.reqXtext.ReqXtextPackage#getXProvider()
 * @model
 * @generated
 */
public interface XProvider extends XAgent
{
} // XProvider
