/**
 * generated by Xtext 2.12.0
 */
package xtextImplementation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import xtextImplementation.ui.AbstractXtextImplUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XtextImplUiModule extends AbstractXtextImplUiModule {
  public XtextImplUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
