/*
 * generated by Xtext 2.11.0
 */
package requirementsXtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ReqXtextGrammarAccess extends AbstractGrammarElementFinder {
	
	public class XContainerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirementsXtext.ReqXtext.XContainer");
		private final Assignment cAgentsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cAgentsXAgentParserRuleCall_0 = (RuleCall)cAgentsAssignment.eContents().get(0);
		
		//XContainer:
		//	agents+=XAgent*;
		@Override public ParserRule getRule() { return rule; }
		
		//agents+=XAgent*
		public Assignment getAgentsAssignment() { return cAgentsAssignment; }
		
		//XAgent
		public RuleCall getAgentsXAgentParserRuleCall_0() { return cAgentsXAgentParserRuleCall_0; }
	}
	public class XAgentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirementsXtext.ReqXtext.XAgent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cXProviderParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cXConsumerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//XAgent:
		//	XProvider | XConsumer;
		@Override public ParserRule getRule() { return rule; }
		
		//XProvider | XConsumer
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//XProvider
		public RuleCall getXProviderParserRuleCall_0() { return cXProviderParserRuleCall_0; }
		
		//XConsumer
		public RuleCall getXConsumerParserRuleCall_1() { return cXConsumerParserRuleCall_1; }
	}
	public class EBigIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirementsXtext.ReqXtext.EBigInteger");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EBigInteger ecore::EBigInteger:
		//	INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class XProviderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirementsXtext.ReqXtext.XProvider");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProviderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSpeedKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSpeedAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSpeedEBigIntegerParserRuleCall_4_0 = (RuleCall)cSpeedAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//XProvider:
		//	'Provider'
		//	name=ID
		//	'{'
		//	'speed' speed=EBigInteger
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Provider' name=ID '{' 'speed' speed=EBigInteger '}'
		public Group getGroup() { return cGroup; }
		
		//'Provider'
		public Keyword getProviderKeyword_0() { return cProviderKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'speed'
		public Keyword getSpeedKeyword_3() { return cSpeedKeyword_3; }
		
		//speed=EBigInteger
		public Assignment getSpeedAssignment_4() { return cSpeedAssignment_4; }
		
		//EBigInteger
		public RuleCall getSpeedEBigIntegerParserRuleCall_4_0() { return cSpeedEBigIntegerParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class XConsumerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "requirementsXtext.ReqXtext.XConsumer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConsumerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSpeedKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSpeedAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSpeedEBigIntegerParserRuleCall_4_0 = (RuleCall)cSpeedAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//XConsumer:
		//	'Consumer'
		//	name=ID
		//	'{'
		//	'speed' speed=EBigInteger
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Consumer' name=ID '{' 'speed' speed=EBigInteger '}'
		public Group getGroup() { return cGroup; }
		
		//'Consumer'
		public Keyword getConsumerKeyword_0() { return cConsumerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'speed'
		public Keyword getSpeedKeyword_3() { return cSpeedKeyword_3; }
		
		//speed=EBigInteger
		public Assignment getSpeedAssignment_4() { return cSpeedAssignment_4; }
		
		//EBigInteger
		public RuleCall getSpeedEBigIntegerParserRuleCall_4_0() { return cSpeedEBigIntegerParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private final XContainerElements pXContainer;
	private final XAgentElements pXAgent;
	private final EBigIntegerElements pEBigInteger;
	private final XProviderElements pXProvider;
	private final XConsumerElements pXConsumer;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ReqXtextGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pXContainer = new XContainerElements();
		this.pXAgent = new XAgentElements();
		this.pEBigInteger = new EBigIntegerElements();
		this.pXProvider = new XProviderElements();
		this.pXConsumer = new XConsumerElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("requirementsXtext.ReqXtext".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//XContainer:
	//	agents+=XAgent*;
	public XContainerElements getXContainerAccess() {
		return pXContainer;
	}
	
	public ParserRule getXContainerRule() {
		return getXContainerAccess().getRule();
	}
	
	//XAgent:
	//	XProvider | XConsumer;
	public XAgentElements getXAgentAccess() {
		return pXAgent;
	}
	
	public ParserRule getXAgentRule() {
		return getXAgentAccess().getRule();
	}
	
	//EBigInteger ecore::EBigInteger:
	//	INT;
	public EBigIntegerElements getEBigIntegerAccess() {
		return pEBigInteger;
	}
	
	public ParserRule getEBigIntegerRule() {
		return getEBigIntegerAccess().getRule();
	}
	
	//XProvider:
	//	'Provider'
	//	name=ID
	//	'{'
	//	'speed' speed=EBigInteger
	//	'}';
	public XProviderElements getXProviderAccess() {
		return pXProvider;
	}
	
	public ParserRule getXProviderRule() {
		return getXProviderAccess().getRule();
	}
	
	//XConsumer:
	//	'Consumer'
	//	name=ID
	//	'{'
	//	'speed' speed=EBigInteger
	//	'}';
	public XConsumerElements getXConsumerAccess() {
		return pXConsumer;
	}
	
	public ParserRule getXConsumerRule() {
		return getXConsumerAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
