/*
 * generated by Xtext 2.11.0
 */
package xtextImplementation.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import xtextImplementation.services.XtextImplGrammarAccess;
import xtextImplementation.xtextImpl.CableAttributes;
import xtextImplementation.xtextImpl.Connections;
import xtextImplementation.xtextImpl.XComputer;
import xtextImplementation.xtextImpl.XContainer;
import xtextImplementation.xtextImpl.XCopperCable;
import xtextImplementation.xtextImpl.XGlassFiberCable;
import xtextImplementation.xtextImpl.XRouter;
import xtextImplementation.xtextImpl.XServer;
import xtextImplementation.xtextImpl.XtextImplPackage;

@SuppressWarnings("all")
public class XtextImplSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private XtextImplGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == XtextImplPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case XtextImplPackage.CABLE_ATTRIBUTES:
				sequence_CableAttributes(context, (CableAttributes) semanticObject); 
				return; 
			case XtextImplPackage.CONNECTIONS:
				sequence_Connections(context, (Connections) semanticObject); 
				return; 
			case XtextImplPackage.XCOMPUTER:
				sequence_XComputer(context, (XComputer) semanticObject); 
				return; 
			case XtextImplPackage.XCONTAINER:
				sequence_XContainer(context, (XContainer) semanticObject); 
				return; 
			case XtextImplPackage.XCOPPER_CABLE:
				sequence_XCopperCable(context, (XCopperCable) semanticObject); 
				return; 
			case XtextImplPackage.XGLASS_FIBER_CABLE:
				sequence_XGlassFiberCable(context, (XGlassFiberCable) semanticObject); 
				return; 
			case XtextImplPackage.XROUTER:
				sequence_XRouter(context, (XRouter) semanticObject); 
				return; 
			case XtextImplPackage.XSERVER:
				sequence_XServer(context, (XServer) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     CableAttributes returns CableAttributes
	 *
	 * Constraint:
	 *     (speed=EBigInteger endPoint1=[XDevice|ID] endPoint2=[XDevice|ID] isDuplex=bool?)
	 */
	protected void sequence_CableAttributes(ISerializationContext context, CableAttributes semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Connections returns Connections
	 *
	 * Constraint:
	 *     ((incoming+=[XCable|ID] incoming+=[XCable|ID]*)? (outgoing+=[XCable|ID] outgoing+=[XCable|ID]*)?)
	 */
	protected void sequence_Connections(ISerializationContext context, Connections semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     NetworkElement returns XComputer
	 *     XDevice returns XComputer
	 *     XComputer returns XComputer
	 *
	 * Constraint:
	 *     (name=ID connections=Connections)
	 */
	protected void sequence_XComputer(ISerializationContext context, XComputer semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME));
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.XDEVICE__CONNECTIONS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.XDEVICE__CONNECTIONS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXComputerAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXComputerAccess().getConnectionsConnectionsParserRuleCall_3_0(), semanticObject.getConnections());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     XContainer returns XContainer
	 *
	 * Constraint:
	 *     elements+=NetworkElement+
	 */
	protected void sequence_XContainer(ISerializationContext context, XContainer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     NetworkElement returns XCopperCable
	 *     XCable returns XCopperCable
	 *     XCopperCable returns XCopperCable
	 *
	 * Constraint:
	 *     (name=ID cableAttributes=CableAttributes)
	 */
	protected void sequence_XCopperCable(ISerializationContext context, XCopperCable semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME));
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.XCABLE__CABLE_ATTRIBUTES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.XCABLE__CABLE_ATTRIBUTES));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXCopperCableAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXCopperCableAccess().getCableAttributesCableAttributesParserRuleCall_3_0(), semanticObject.getCableAttributes());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     NetworkElement returns XGlassFiberCable
	 *     XCable returns XGlassFiberCable
	 *     XGlassFiberCable returns XGlassFiberCable
	 *
	 * Constraint:
	 *     (name=ID cableAttributes=CableAttributes)
	 */
	protected void sequence_XGlassFiberCable(ISerializationContext context, XGlassFiberCable semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME));
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.XCABLE__CABLE_ATTRIBUTES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.XCABLE__CABLE_ATTRIBUTES));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXGlassFiberCableAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXGlassFiberCableAccess().getCableAttributesCableAttributesParserRuleCall_3_0(), semanticObject.getCableAttributes());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     NetworkElement returns XRouter
	 *     XDevice returns XRouter
	 *     XRouter returns XRouter
	 *
	 * Constraint:
	 *     (name=ID maxSpeed=EBigInteger connections=Connections)
	 */
	protected void sequence_XRouter(ISerializationContext context, XRouter semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME));
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.XROUTER__MAX_SPEED) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.XROUTER__MAX_SPEED));
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.XDEVICE__CONNECTIONS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.XDEVICE__CONNECTIONS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXRouterAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXRouterAccess().getMaxSpeedEBigIntegerParserRuleCall_4_0(), semanticObject.getMaxSpeed());
		feeder.accept(grammarAccess.getXRouterAccess().getConnectionsConnectionsParserRuleCall_5_0(), semanticObject.getConnections());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     NetworkElement returns XServer
	 *     XDevice returns XServer
	 *     XServer returns XServer
	 *
	 * Constraint:
	 *     (name=ID maxSlots=EBigInteger MTBF=EBigInteger connections=Connections)
	 */
	protected void sequence_XServer(ISerializationContext context, XServer semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.NETWORK_ELEMENTS__NAME));
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.XSERVER__MAX_SLOTS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.XSERVER__MAX_SLOTS));
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.XSERVER__MTBF) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.XSERVER__MTBF));
			if (transientValues.isValueTransient(semanticObject, XtextImplPackage.Literals.XDEVICE__CONNECTIONS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XtextImplPackage.Literals.XDEVICE__CONNECTIONS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXServerAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXServerAccess().getMaxSlotsEBigIntegerParserRuleCall_4_0(), semanticObject.getMaxSlots());
		feeder.accept(grammarAccess.getXServerAccess().getMTBFEBigIntegerParserRuleCall_6_0(), semanticObject.getMTBF());
		feeder.accept(grammarAccess.getXServerAccess().getConnectionsConnectionsParserRuleCall_7_0(), semanticObject.getConnections());
		feeder.finish();
	}
	
	
}
