/**
 * generated by Xtext 2.10.0
 */
package requirementsXtext;

import requirementsXtext.ReqXtextStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReqXtextStandaloneSetup extends ReqXtextStandaloneSetupGenerated {
  public static void doSetup() {
    new ReqXtextStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
