/*
 * generated by Xtext 2.11.0
 */
package requirementsXtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReqXtextAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("requirementsXtext/parser/antlr/internal/InternalReqXtext.tokens");
	}
}
