/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;

import java.math.BigInteger;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cable Attributes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.CableAttributes#getSpeed <em>Speed</em>}</li>
 *   <li>{@link xtextImplementation.xtextImpl.CableAttributes#getEndPoint1 <em>End Point1</em>}</li>
 *   <li>{@link xtextImplementation.xtextImpl.CableAttributes#getEndPoint2 <em>End Point2</em>}</li>
 *   <li>{@link xtextImplementation.xtextImpl.CableAttributes#isIsDuplex <em>Is Duplex</em>}</li>
 * </ul>
 *
 * @see xtextImplementation.xtextImpl.XtextImplPackage#getCableAttributes()
 * @model
 * @generated
 */
public interface CableAttributes extends EObject
{
  /**
   * Returns the value of the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' attribute.
   * @see #setSpeed(BigInteger)
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getCableAttributes_Speed()
   * @model
   * @generated
   */
  BigInteger getSpeed();

  /**
   * Sets the value of the '{@link xtextImplementation.xtextImpl.CableAttributes#getSpeed <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' attribute.
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(BigInteger value);

  /**
   * Returns the value of the '<em><b>End Point1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End Point1</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Point1</em>' reference.
   * @see #setEndPoint1(XDevice)
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getCableAttributes_EndPoint1()
   * @model
   * @generated
   */
  XDevice getEndPoint1();

  /**
   * Sets the value of the '{@link xtextImplementation.xtextImpl.CableAttributes#getEndPoint1 <em>End Point1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Point1</em>' reference.
   * @see #getEndPoint1()
   * @generated
   */
  void setEndPoint1(XDevice value);

  /**
   * Returns the value of the '<em><b>End Point2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End Point2</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Point2</em>' reference.
   * @see #setEndPoint2(XDevice)
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getCableAttributes_EndPoint2()
   * @model
   * @generated
   */
  XDevice getEndPoint2();

  /**
   * Sets the value of the '{@link xtextImplementation.xtextImpl.CableAttributes#getEndPoint2 <em>End Point2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Point2</em>' reference.
   * @see #getEndPoint2()
   * @generated
   */
  void setEndPoint2(XDevice value);

  /**
   * Returns the value of the '<em><b>Is Duplex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Duplex</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Duplex</em>' attribute.
   * @see #setIsDuplex(boolean)
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getCableAttributes_IsDuplex()
   * @model
   * @generated
   */
  boolean isIsDuplex();

  /**
   * Sets the value of the '{@link xtextImplementation.xtextImpl.CableAttributes#isIsDuplex <em>Is Duplex</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Duplex</em>' attribute.
   * @see #isIsDuplex()
   * @generated
   */
  void setIsDuplex(boolean value);

} // CableAttributes
