/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connections</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.Connections#getIncoming <em>Incoming</em>}</li>
 *   <li>{@link xtextImplementation.xtextImpl.Connections#getOutgoing <em>Outgoing</em>}</li>
 * </ul>
 *
 * @see xtextImplementation.xtextImpl.XtextImplPackage#getConnections()
 * @model
 * @generated
 */
public interface Connections extends EObject
{
  /**
   * Returns the value of the '<em><b>Incoming</b></em>' reference list.
   * The list contents are of type {@link xtextImplementation.xtextImpl.XCable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Incoming</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Incoming</em>' reference list.
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getConnections_Incoming()
   * @model
   * @generated
   */
  EList<XCable> getIncoming();

  /**
   * Returns the value of the '<em><b>Outgoing</b></em>' reference list.
   * The list contents are of type {@link xtextImplementation.xtextImpl.XCable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Outgoing</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outgoing</em>' reference list.
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getConnections_Outgoing()
   * @model
   * @generated
   */
  EList<XCable> getOutgoing();

} // Connections
