/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XComputer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtextImplementation.xtextImpl.XtextImplPackage#getXComputer()
 * @model
 * @generated
 */
public interface XComputer extends XDevice
{
} // XComputer
