/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XContainer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.XContainer#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see xtextImplementation.xtextImpl.XtextImplPackage#getXContainer()
 * @model
 * @generated
 */
public interface XContainer extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link xtextImplementation.xtextImpl.NetworkElements}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getXContainer_Elements()
   * @model containment="true"
   * @generated
   */
  EList<NetworkElements> getElements();

} // XContainer
