/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XCopper Cable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtextImplementation.xtextImpl.XtextImplPackage#getXCopperCable()
 * @model
 * @generated
 */
public interface XCopperCable extends XCable
{
} // XCopperCable
