/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XDevice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.XDevice#getConnections <em>Connections</em>}</li>
 * </ul>
 *
 * @see xtextImplementation.xtextImpl.XtextImplPackage#getXDevice()
 * @model
 * @generated
 */
public interface XDevice extends NetworkElements
{
  /**
   * Returns the value of the '<em><b>Connections</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Connections</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connections</em>' containment reference.
   * @see #setConnections(Connections)
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getXDevice_Connections()
   * @model containment="true"
   * @generated
   */
  Connections getConnections();

  /**
   * Sets the value of the '{@link xtextImplementation.xtextImpl.XDevice#getConnections <em>Connections</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Connections</em>' containment reference.
   * @see #getConnections()
   * @generated
   */
  void setConnections(Connections value);

} // XDevice
