/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XGlass Fiber Cable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtextImplementation.xtextImpl.XtextImplPackage#getXGlassFiberCable()
 * @model
 * @generated
 */
public interface XGlassFiberCable extends XCable
{
} // XGlassFiberCable
