/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;

import java.math.BigInteger;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XServer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtextImplementation.xtextImpl.XServer#getMaxSlots <em>Max Slots</em>}</li>
 *   <li>{@link xtextImplementation.xtextImpl.XServer#getMTBF <em>MTBF</em>}</li>
 * </ul>
 *
 * @see xtextImplementation.xtextImpl.XtextImplPackage#getXServer()
 * @model
 * @generated
 */
public interface XServer extends XDevice
{
  /**
   * Returns the value of the '<em><b>Max Slots</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Slots</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Slots</em>' attribute.
   * @see #setMaxSlots(BigInteger)
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getXServer_MaxSlots()
   * @model
   * @generated
   */
  BigInteger getMaxSlots();

  /**
   * Sets the value of the '{@link xtextImplementation.xtextImpl.XServer#getMaxSlots <em>Max Slots</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Slots</em>' attribute.
   * @see #getMaxSlots()
   * @generated
   */
  void setMaxSlots(BigInteger value);

  /**
   * Returns the value of the '<em><b>MTBF</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>MTBF</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>MTBF</em>' attribute.
   * @see #setMTBF(BigInteger)
   * @see xtextImplementation.xtextImpl.XtextImplPackage#getXServer_MTBF()
   * @model
   * @generated
   */
  BigInteger getMTBF();

  /**
   * Sets the value of the '{@link xtextImplementation.xtextImpl.XServer#getMTBF <em>MTBF</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MTBF</em>' attribute.
   * @see #getMTBF()
   * @generated
   */
  void setMTBF(BigInteger value);

} // XServer
