/**
 * generated by Xtext 2.11.0
 */
package xtextImplementation.xtextImpl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtextImplementation.xtextImpl.XtextImplFactory
 * @model kind="package"
 * @generated
 */
public interface XtextImplPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xtextImpl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "platform:/plugin/xtextImplementation/model/generated/XtextImpl.ecore";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xtextImpl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XtextImplPackage eINSTANCE = xtextImplementation.xtextImpl.impl.XtextImplPackageImpl.init();

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.XContainerImpl <em>XContainer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.XContainerImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXContainer()
   * @generated
   */
  int XCONTAINER = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCONTAINER__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>XContainer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCONTAINER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.NetworkElementsImpl <em>Network Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.NetworkElementsImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getNetworkElements()
   * @generated
   */
  int NETWORK_ELEMENTS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK_ELEMENTS__NAME = 0;

  /**
   * The number of structural features of the '<em>Network Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK_ELEMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.XDeviceImpl <em>XDevice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.XDeviceImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXDevice()
   * @generated
   */
  int XDEVICE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XDEVICE__NAME = NETWORK_ELEMENTS__NAME;

  /**
   * The feature id for the '<em><b>Connections</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XDEVICE__CONNECTIONS = NETWORK_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>XDevice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XDEVICE_FEATURE_COUNT = NETWORK_ELEMENTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.XCableImpl <em>XCable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.XCableImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXCable()
   * @generated
   */
  int XCABLE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCABLE__NAME = NETWORK_ELEMENTS__NAME;

  /**
   * The feature id for the '<em><b>Cable Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCABLE__CABLE_ATTRIBUTES = NETWORK_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>XCable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCABLE_FEATURE_COUNT = NETWORK_ELEMENTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.ConnectionsImpl <em>Connections</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.ConnectionsImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getConnections()
   * @generated
   */
  int CONNECTIONS = 4;

  /**
   * The feature id for the '<em><b>Incoming</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTIONS__INCOMING = 0;

  /**
   * The feature id for the '<em><b>Outgoing</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTIONS__OUTGOING = 1;

  /**
   * The number of structural features of the '<em>Connections</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.CableAttributesImpl <em>Cable Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.CableAttributesImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getCableAttributes()
   * @generated
   */
  int CABLE_ATTRIBUTES = 5;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CABLE_ATTRIBUTES__SPEED = 0;

  /**
   * The feature id for the '<em><b>End Point1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CABLE_ATTRIBUTES__END_POINT1 = 1;

  /**
   * The feature id for the '<em><b>End Point2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CABLE_ATTRIBUTES__END_POINT2 = 2;

  /**
   * The feature id for the '<em><b>Is Duplex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CABLE_ATTRIBUTES__IS_DUPLEX = 3;

  /**
   * The number of structural features of the '<em>Cable Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CABLE_ATTRIBUTES_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.XServerImpl <em>XServer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.XServerImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXServer()
   * @generated
   */
  int XSERVER = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSERVER__NAME = XDEVICE__NAME;

  /**
   * The feature id for the '<em><b>Connections</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSERVER__CONNECTIONS = XDEVICE__CONNECTIONS;

  /**
   * The feature id for the '<em><b>Max Slots</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSERVER__MAX_SLOTS = XDEVICE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>MTBF</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSERVER__MTBF = XDEVICE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>XServer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSERVER_FEATURE_COUNT = XDEVICE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.XComputerImpl <em>XComputer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.XComputerImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXComputer()
   * @generated
   */
  int XCOMPUTER = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCOMPUTER__NAME = XDEVICE__NAME;

  /**
   * The feature id for the '<em><b>Connections</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCOMPUTER__CONNECTIONS = XDEVICE__CONNECTIONS;

  /**
   * The number of structural features of the '<em>XComputer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCOMPUTER_FEATURE_COUNT = XDEVICE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.XRouterImpl <em>XRouter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.XRouterImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXRouter()
   * @generated
   */
  int XROUTER = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XROUTER__NAME = XDEVICE__NAME;

  /**
   * The feature id for the '<em><b>Connections</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XROUTER__CONNECTIONS = XDEVICE__CONNECTIONS;

  /**
   * The feature id for the '<em><b>Max Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XROUTER__MAX_SPEED = XDEVICE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>XRouter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XROUTER_FEATURE_COUNT = XDEVICE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.XCopperCableImpl <em>XCopper Cable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.XCopperCableImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXCopperCable()
   * @generated
   */
  int XCOPPER_CABLE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCOPPER_CABLE__NAME = XCABLE__NAME;

  /**
   * The feature id for the '<em><b>Cable Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCOPPER_CABLE__CABLE_ATTRIBUTES = XCABLE__CABLE_ATTRIBUTES;

  /**
   * The number of structural features of the '<em>XCopper Cable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XCOPPER_CABLE_FEATURE_COUNT = XCABLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xtextImplementation.xtextImpl.impl.XGlassFiberCableImpl <em>XGlass Fiber Cable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtextImplementation.xtextImpl.impl.XGlassFiberCableImpl
   * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXGlassFiberCable()
   * @generated
   */
  int XGLASS_FIBER_CABLE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XGLASS_FIBER_CABLE__NAME = XCABLE__NAME;

  /**
   * The feature id for the '<em><b>Cable Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XGLASS_FIBER_CABLE__CABLE_ATTRIBUTES = XCABLE__CABLE_ATTRIBUTES;

  /**
   * The number of structural features of the '<em>XGlass Fiber Cable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XGLASS_FIBER_CABLE_FEATURE_COUNT = XCABLE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.XContainer <em>XContainer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XContainer</em>'.
   * @see xtextImplementation.xtextImpl.XContainer
   * @generated
   */
  EClass getXContainer();

  /**
   * Returns the meta object for the containment reference list '{@link xtextImplementation.xtextImpl.XContainer#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see xtextImplementation.xtextImpl.XContainer#getElements()
   * @see #getXContainer()
   * @generated
   */
  EReference getXContainer_Elements();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.NetworkElements <em>Network Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Network Elements</em>'.
   * @see xtextImplementation.xtextImpl.NetworkElements
   * @generated
   */
  EClass getNetworkElements();

  /**
   * Returns the meta object for the attribute '{@link xtextImplementation.xtextImpl.NetworkElements#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtextImplementation.xtextImpl.NetworkElements#getName()
   * @see #getNetworkElements()
   * @generated
   */
  EAttribute getNetworkElements_Name();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.XDevice <em>XDevice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XDevice</em>'.
   * @see xtextImplementation.xtextImpl.XDevice
   * @generated
   */
  EClass getXDevice();

  /**
   * Returns the meta object for the containment reference '{@link xtextImplementation.xtextImpl.XDevice#getConnections <em>Connections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Connections</em>'.
   * @see xtextImplementation.xtextImpl.XDevice#getConnections()
   * @see #getXDevice()
   * @generated
   */
  EReference getXDevice_Connections();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.XCable <em>XCable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XCable</em>'.
   * @see xtextImplementation.xtextImpl.XCable
   * @generated
   */
  EClass getXCable();

  /**
   * Returns the meta object for the containment reference '{@link xtextImplementation.xtextImpl.XCable#getCableAttributes <em>Cable Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cable Attributes</em>'.
   * @see xtextImplementation.xtextImpl.XCable#getCableAttributes()
   * @see #getXCable()
   * @generated
   */
  EReference getXCable_CableAttributes();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.Connections <em>Connections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connections</em>'.
   * @see xtextImplementation.xtextImpl.Connections
   * @generated
   */
  EClass getConnections();

  /**
   * Returns the meta object for the reference list '{@link xtextImplementation.xtextImpl.Connections#getIncoming <em>Incoming</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Incoming</em>'.
   * @see xtextImplementation.xtextImpl.Connections#getIncoming()
   * @see #getConnections()
   * @generated
   */
  EReference getConnections_Incoming();

  /**
   * Returns the meta object for the reference list '{@link xtextImplementation.xtextImpl.Connections#getOutgoing <em>Outgoing</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Outgoing</em>'.
   * @see xtextImplementation.xtextImpl.Connections#getOutgoing()
   * @see #getConnections()
   * @generated
   */
  EReference getConnections_Outgoing();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.CableAttributes <em>Cable Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cable Attributes</em>'.
   * @see xtextImplementation.xtextImpl.CableAttributes
   * @generated
   */
  EClass getCableAttributes();

  /**
   * Returns the meta object for the attribute '{@link xtextImplementation.xtextImpl.CableAttributes#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see xtextImplementation.xtextImpl.CableAttributes#getSpeed()
   * @see #getCableAttributes()
   * @generated
   */
  EAttribute getCableAttributes_Speed();

  /**
   * Returns the meta object for the reference '{@link xtextImplementation.xtextImpl.CableAttributes#getEndPoint1 <em>End Point1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>End Point1</em>'.
   * @see xtextImplementation.xtextImpl.CableAttributes#getEndPoint1()
   * @see #getCableAttributes()
   * @generated
   */
  EReference getCableAttributes_EndPoint1();

  /**
   * Returns the meta object for the reference '{@link xtextImplementation.xtextImpl.CableAttributes#getEndPoint2 <em>End Point2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>End Point2</em>'.
   * @see xtextImplementation.xtextImpl.CableAttributes#getEndPoint2()
   * @see #getCableAttributes()
   * @generated
   */
  EReference getCableAttributes_EndPoint2();

  /**
   * Returns the meta object for the attribute '{@link xtextImplementation.xtextImpl.CableAttributes#isIsDuplex <em>Is Duplex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Duplex</em>'.
   * @see xtextImplementation.xtextImpl.CableAttributes#isIsDuplex()
   * @see #getCableAttributes()
   * @generated
   */
  EAttribute getCableAttributes_IsDuplex();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.XServer <em>XServer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XServer</em>'.
   * @see xtextImplementation.xtextImpl.XServer
   * @generated
   */
  EClass getXServer();

  /**
   * Returns the meta object for the attribute '{@link xtextImplementation.xtextImpl.XServer#getMaxSlots <em>Max Slots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Slots</em>'.
   * @see xtextImplementation.xtextImpl.XServer#getMaxSlots()
   * @see #getXServer()
   * @generated
   */
  EAttribute getXServer_MaxSlots();

  /**
   * Returns the meta object for the attribute '{@link xtextImplementation.xtextImpl.XServer#getMTBF <em>MTBF</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>MTBF</em>'.
   * @see xtextImplementation.xtextImpl.XServer#getMTBF()
   * @see #getXServer()
   * @generated
   */
  EAttribute getXServer_MTBF();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.XComputer <em>XComputer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XComputer</em>'.
   * @see xtextImplementation.xtextImpl.XComputer
   * @generated
   */
  EClass getXComputer();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.XRouter <em>XRouter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XRouter</em>'.
   * @see xtextImplementation.xtextImpl.XRouter
   * @generated
   */
  EClass getXRouter();

  /**
   * Returns the meta object for the attribute '{@link xtextImplementation.xtextImpl.XRouter#getMaxSpeed <em>Max Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Speed</em>'.
   * @see xtextImplementation.xtextImpl.XRouter#getMaxSpeed()
   * @see #getXRouter()
   * @generated
   */
  EAttribute getXRouter_MaxSpeed();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.XCopperCable <em>XCopper Cable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XCopper Cable</em>'.
   * @see xtextImplementation.xtextImpl.XCopperCable
   * @generated
   */
  EClass getXCopperCable();

  /**
   * Returns the meta object for class '{@link xtextImplementation.xtextImpl.XGlassFiberCable <em>XGlass Fiber Cable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XGlass Fiber Cable</em>'.
   * @see xtextImplementation.xtextImpl.XGlassFiberCable
   * @generated
   */
  EClass getXGlassFiberCable();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XtextImplFactory getXtextImplFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.XContainerImpl <em>XContainer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.XContainerImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXContainer()
     * @generated
     */
    EClass XCONTAINER = eINSTANCE.getXContainer();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCONTAINER__ELEMENTS = eINSTANCE.getXContainer_Elements();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.NetworkElementsImpl <em>Network Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.NetworkElementsImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getNetworkElements()
     * @generated
     */
    EClass NETWORK_ELEMENTS = eINSTANCE.getNetworkElements();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NETWORK_ELEMENTS__NAME = eINSTANCE.getNetworkElements_Name();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.XDeviceImpl <em>XDevice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.XDeviceImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXDevice()
     * @generated
     */
    EClass XDEVICE = eINSTANCE.getXDevice();

    /**
     * The meta object literal for the '<em><b>Connections</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XDEVICE__CONNECTIONS = eINSTANCE.getXDevice_Connections();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.XCableImpl <em>XCable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.XCableImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXCable()
     * @generated
     */
    EClass XCABLE = eINSTANCE.getXCable();

    /**
     * The meta object literal for the '<em><b>Cable Attributes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XCABLE__CABLE_ATTRIBUTES = eINSTANCE.getXCable_CableAttributes();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.ConnectionsImpl <em>Connections</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.ConnectionsImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getConnections()
     * @generated
     */
    EClass CONNECTIONS = eINSTANCE.getConnections();

    /**
     * The meta object literal for the '<em><b>Incoming</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTIONS__INCOMING = eINSTANCE.getConnections_Incoming();

    /**
     * The meta object literal for the '<em><b>Outgoing</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTIONS__OUTGOING = eINSTANCE.getConnections_Outgoing();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.CableAttributesImpl <em>Cable Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.CableAttributesImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getCableAttributes()
     * @generated
     */
    EClass CABLE_ATTRIBUTES = eINSTANCE.getCableAttributes();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CABLE_ATTRIBUTES__SPEED = eINSTANCE.getCableAttributes_Speed();

    /**
     * The meta object literal for the '<em><b>End Point1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CABLE_ATTRIBUTES__END_POINT1 = eINSTANCE.getCableAttributes_EndPoint1();

    /**
     * The meta object literal for the '<em><b>End Point2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CABLE_ATTRIBUTES__END_POINT2 = eINSTANCE.getCableAttributes_EndPoint2();

    /**
     * The meta object literal for the '<em><b>Is Duplex</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CABLE_ATTRIBUTES__IS_DUPLEX = eINSTANCE.getCableAttributes_IsDuplex();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.XServerImpl <em>XServer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.XServerImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXServer()
     * @generated
     */
    EClass XSERVER = eINSTANCE.getXServer();

    /**
     * The meta object literal for the '<em><b>Max Slots</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XSERVER__MAX_SLOTS = eINSTANCE.getXServer_MaxSlots();

    /**
     * The meta object literal for the '<em><b>MTBF</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XSERVER__MTBF = eINSTANCE.getXServer_MTBF();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.XComputerImpl <em>XComputer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.XComputerImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXComputer()
     * @generated
     */
    EClass XCOMPUTER = eINSTANCE.getXComputer();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.XRouterImpl <em>XRouter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.XRouterImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXRouter()
     * @generated
     */
    EClass XROUTER = eINSTANCE.getXRouter();

    /**
     * The meta object literal for the '<em><b>Max Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XROUTER__MAX_SPEED = eINSTANCE.getXRouter_MaxSpeed();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.XCopperCableImpl <em>XCopper Cable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.XCopperCableImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXCopperCable()
     * @generated
     */
    EClass XCOPPER_CABLE = eINSTANCE.getXCopperCable();

    /**
     * The meta object literal for the '{@link xtextImplementation.xtextImpl.impl.XGlassFiberCableImpl <em>XGlass Fiber Cable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtextImplementation.xtextImpl.impl.XGlassFiberCableImpl
     * @see xtextImplementation.xtextImpl.impl.XtextImplPackageImpl#getXGlassFiberCable()
     * @generated
     */
    EClass XGLASS_FIBER_CABLE = eINSTANCE.getXGlassFiberCable();

  }

} //XtextImplPackage
